# Generated by Django 4.1 on 2023-03-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status_contact',
        ),
    ]
